/* ------------------------------------------------------------------ *
 *  Shared helpers: Stableford conversion + writing data.js
 * ------------------------------------------------------------------ */
import { writeFileSync, copyFileSync, existsSync } from "node:fs";
import { lookupCourse } from "./courses.js";

/* Parse a Wales Golf handicap index string ("21.3" or "+1.3" = plus golfer). */
export function parseHi(s) {
  if (s == null) return null;
  s = String(s).trim();
  if (s === "" || s === "-") return null;
  const plus = s.startsWith("+");
  const n = parseFloat(s.replace("+", ""));
  return Number.isFinite(n) ? (plus ? -n : n) : null;
}

/* Parse an adjusted gross ("101", "*", "" → null for non-scores). */
export function parseGross(s) {
  const n = parseInt(String(s).replace(/[^\d]/g, ""), 10);
  return Number.isFinite(n) ? n : null;
}

/*
 * Convert one round to Stableford points.
 *   Prefer the platform's own Course Handicap when we scraped it (most exact).
 *   Otherwise derive it from Handicap Index + course CR/Slope/Par.
 * Returns { points, courseHcp, par, ok, reason }.
 */
export function toStableford({ adjGross, courseHcp = null, hi = null, course, tee }) {
  const c = lookupCourse(course, tee);
  const par = c ? c.par : null;

  if (adjGross == null) return { points: null, ok: false, reason: "no adjusted gross (NR/incomplete)" };
  if (par == null)      return { points: null, ok: false, reason: `course not in courses.js: "${course} / ${tee}"` };

  if (courseHcp == null) {
    if (hi == null || !c) return { points: null, ok: false, reason: "missing course handicap and can't derive it" };
    courseHcp = Math.round(hi * c.slope / 113 + (c.cr - par));
  }

  const points = 36 + courseHcp + par - adjGross;
  // sanity guard — flags 9-hole rounds or odd data rather than trusting bad points
  const ok = points >= -2 && points <= 54;
  return { points, courseHcp, par, ok, reason: ok ? "" : `points out of range (${points}) — check it's an 18-hole round` };
}

/* Write the dashboard data file the browser reads (window.CHOPPERS_DATA). */
export function writeDataJs(path, competition, players) {
  if (existsSync(path)) copyFileSync(path, path.replace(/\.js$/, ".prev.js")); // backup
  const body =
`/* AUTO-GENERATED by scrape.mjs on ${new Date().toISOString().slice(0, 10)} — do not hand-edit. */
window.CHOPPERS_DATA = ${JSON.stringify({ competition, players }, null, 2)};
`;
  writeFileSync(path, body);
}
